/*
 *
 * PledgesPage constants
 *
 */

export const LOAD_ALL_USERS_ACTION = 'app/PledgesPage/LOAD_ALL_USERS_ACTION';
export const LOAD_ALL_USERS_ACTION_SUCCESS =
  'app/PledgesPage/LOAD_ALL_USERS_ACTION_SUCCESS';
export const LOAD_ALL_USERS_ACTION_ERROR =
  'app/PledgesPage/LOAD_ALL_USERS_ACTION_ERROR';

export const LOAD_THRESHOLDS_ACTION = 'app/PledgesPage/LOAD_THRESHOLDS_ACTION';
export const LOAD_THRESHOLDS_ACTION_SUCCESS =
  'app/PledgesPage/LOAD_THRESHOLDS_ACTION_SUCCESS';
export const LOAD_THRESHOLDS_ACTION_ERROR =
  'app/PledgesPage/LOAD_THRESHOLDS_ACTION_ERROR';

export const LOAD_CD_W_USERS_ACTION = 'app/PledgesPage/LOAD_CD_W_USERS_ACTION';
export const LOAD_CD_W_USERS_ACTION_SUCCESS =
  'app/PledgesPage/LOAD_CD_W_USERS_ACTION_SUCCESS';
export const LOAD_CD_W_USERS_ACTION_ERROR =
  'app/PledgesPage/LOAD_CD_W_USERS_ACTION_ERROR';

export const LOAD_SENATE_W_USERS_ACTION =
  'app/PledgesPage/LOAD_SENATE_W_USERS_ACTION';
export const LOAD_SENATE_W_USERS_ACTION_SUCCESS =
  'app/PledgesPage/LOAD_SENATE_W_USERS_ACTION_SUCCESS';
export const LOAD_SENATE_W_USERS_ACTION_ERROR =
  'app/PledgesPage/LOAD_SENATE_W_USERS_ACTION_ERROR';
