export const LOGIN_USER_ACTION = '@@TGP_ADMIN/APP/LOGIN_USER';
export const LOGIN_USER_ACTION_SUCCESS = '@@TGP_ADMIN/APP/LOGIN_USER_SUCCESS';
export const LOGIN_USER_ACTION_ERROR = '@@TGP_ADMIN/APP/LOGIN_USER_ERROR';

export const LOAD_USER_ACTION = '@@TGP_ADMIN/APP/LOAD_USER';

export const RESET_USER_ACTION = '@@TGP_ADMIN/APP/RESET_USER';

export const VERIFY_PHONE_ACTION = '@@TGP_ADMIN/APP/VERIFY_PHONE';
export const VERIFY_PHONE_ACTION_SUCCESS = '@@TGP_ADMIN/APP/VERIFY_PHONE_SUCCESS';
export const VERIFY_PHONE_ACTION_ERROR = '@@TGP_ADMIN/APP/VERIFY_PHONE_ERROR';
